<a href="https://colab.research.google.com/github/JuanSCalderon/MinTic/blob/main/Copia_de_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introducción Numpy

In [ ]:
listapy = [[5,7,8], [1,2,3]]
print(listapy)


[[5, 7, 8], [1, 2, 3]]


In [ ]:
import numpy as np

listapy = [5,7,8]
lista = np.array([5,7,8])
print(lista)
print("\n")
print(listapy)


[5 7 8]


[5, 7, 8]


In [ ]:
matrizPy = [[1,2,3], [7,8,9]]
print(matrizPy)

[[1, 2, 3], [7, 8, 9]]


In [ ]:
matrizNp = np.array([[1,2,3], [7,8,9]])
print(matrizNp)


[[1 2 3]
 [7 8 9]]


##Matrices "Vacias"

In [ ]:
matriz = [["Johan", "Paula", "Marc", "David"], [14,21,23, 15], ["Portección", "Porvenir", "ColPensiones", "Porvenir"]]
for i in range(0,3,1): #0,1,2 asignación: i = valor inicial, i += 1, if(i < valor final) i-> Filas
  for j in range(0,4,1): #0,1,2,3 -> J -> Columnas
    matriz[i][j] = 1

print(matriz)

[[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]


In [ ]:
# Formas de inicializar las matrices para su posterior seteo, o asignación

# Crear una matriz de unos - 3 filas 4 columnas
unos = np.ones((3,4))
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Crear una matriz de ceros - 3 filas 4 columnas
ceros = np.zeros((3,4))
print(ceros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# Crear una matriz con valores aleatorios
aleatorios = np.random.random((2,2))
print(aleatorios)

[[0.43037655 0.53016528]
 [0.16327291 0.17279816]]


In [ ]:
# Crear una matriz vacía
vacia = np.empty((3,2))
print(vacia)

[[3.38837493e-316 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [ ]:
# Crear una matriz con un solo valor
full = np.full((10,10),8)
print(full)

[[8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]]


In [ ]:
# Crear una matriz con valores espaciados uniformemente
espacio1 = np.arange(0,30,5)
print(espacio1)

[ 0  5 10 15 20 25]


In [ ]:
# 5 valores entre 0 y 2 distribuidos uniformemente
espacio2 = np.linspace(0,2,5)
print(espacio2)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
# Crear una matriz identidad (Algebra lineal)
identidad1 = np.eye(4,5)
print(identidad1)
print("")
identidad2 = np.identity(10)
print(identidad2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
print(type(identidad1[1][1]))

<class 'numpy.float64'>


##Información sobre las matrices

In [ ]:
# Conocer las dimensiones de una matriz
a = np.array([(1,2,3),(4,5,6)])
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
# Conocer el tipo de los datos
a = np.array([(1,2,3)])
print(a.dtype)

int64


In [ ]:
# Conocer el tamaño y forma de la matriz
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


In [ ]:
# Cambio de forma de una matriz (valor columna a fila, valor de fila a columna)
a = np.array([(8,9,10),(11,12,13)])
print(a)
a=a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [ ]:
# Extraer un solo valor de la matriz - el valor ubicado en la fila 0 columna 2
a = np.array([(1,2,3,4),(3,4,5,6)])
print(a)
print(a[0,2])

[[1 2 3 4]
 [3 4 5 6]]
3


También podemos referenciar múltiples elementos de un arreglo NumPy usando los dos puntos. Por ejemplo, el índice [2:] selecciona cada elemento desde el índice 2 en adelante. El índice [:3] selecciona cada elemento hasta el índice 3 excluido. El índice [2:4] retorna cada elemento desde el índice 2 al índice 4, excluyendo este último. 

In [ ]:
#                 0 1 2 3 4 5 6 7 8 9
lista = np.array([1,2,3,4,5,6,7,8,9,0])
print(lista)

[1 2 3 4 5 6 7 8 9 0]


In [ ]:
print(lista[:])

[1 2 3 4 5 6 7 8 9 0]


In [ ]:
print(lista[2:])

[3 4 5 6 7 8 9 0]


In [ ]:
print(lista[:3])

[1 2 3]


In [ ]:
print(lista[2:4]) #Desde el valor inicial, hasta < valor final (Uno menos)  Rango -> valor inicial <= lista < valor final

[3 4]


In [ ]:
# Extraer los valores de todas las filas ubicados en la columna 3 
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a)
print(a[0:,2]) #[0][2]
#               [1][2] 

[[1 2 3 4]
 [3 4 5 6]]
[3 5]


##Operaciones matematicas

In [ ]:
# Encontrar el mínimo, máximo y la suma
a= np.array([2,4,8])
print(a.min())
print(a.max())
print(a.sum())

2
8
14


In [ ]:
# Calcular la raíz cuadrada y la desviación estándar
a=np.array([(1,2,3),(3,4,5)])
print(np.sqrt(a))
print(np.std(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056


In [ ]:
m1 = [[1,2,3],[1,2,3],[1,2,3]]
m2 = [[1,2,3],[1,2,3],[1,2,3]]
print(m1)
print()
print(m2)

print(m1+m2)

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [ ]:
# Calcular la suma, resta, multiplicación y división de dos matrices
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x)
print(y)
print("Suma")
print(x+y)
print("Resta")
print(x-y)
print("Multiplicación")
print(x*y)
print("División")
print(x/y)

[[1 2 3]
 [3 4 5]]
[[1 2 3]
 [3 4 5]]
Suma
[[ 2  4  6]
 [ 6  8 10]]
Resta
[[0 0 0]
 [0 0 0]]
Multiplicación
[[ 1  4  9]
 [ 9 16 25]]
División
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#Igualmente puedo realizar las operaciones con numeros enteros
print(x)
print()
print("Suma + 5 todos los datos")
print(x + 2)
print()
#Resta, multiplicación y división
print(x - 2)
print()
print(x * 2)
print()
print(x/2)

[[1 2 3]
 [3 4 5]]

Suma + 5 todos los datos
[[3 4 5]
 [5 6 7]]

[[-1  0  1]
 [ 1  2  3]]

[[ 2  4  6]
 [ 6  8 10]]

[[0.5 1.  1.5]
 [1.5 2.  2.5]]


In [ ]:
#Función Round con numpy a toda una mtriz
arr_uni = np.random.rand(5)
print(arr_uni)

[0.95370159 0.19173965 0.96168314 0.21199967 0.41564064]


In [ ]:
arr_uni = np.round(arr_uni, 2)
print(arr_uni)

[0.6  0.88 0.72 0.49 0.55]


## Extra (secret crazy)

In [ ]:
arr = np.array([0.69, 0.94, 0.66, 0.73, 0.83])

arr > 0.7


array([False,  True, False,  True,  True])