<a href="https://colab.research.google.com/github/JuanSCalderon/MinTic/blob/main/Modulo4_Grupo11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Diccionarios.

In [ ]:
A = {'Col 1': 22, 'Col 2': 9.8, 'Col 3': 'Hola'}
print(A)

{'Col 1': 22, 'Col 2': 9.8, 'Col 3': 'Hola'}


In [ ]:
A = {'Col 1': [22, 324, 99, 1000], 'Col 2': [9.8, 5.6, 23.5, 10]}
print(A)

{'Col 1': [22, 324, 99, 1000], 'Col 2': [9.8, 5.6, 23.5, 10]}


In [ ]:
A = {1: [22, 324, 99, 100], 4.5: [3.4, 4, 8, 2.0]}
print(A)

{1: [22, 324, 99, 100], 4.5: [3.4, 4, 8, 2.0]}


In [ ]:
A[4.5][1]

4

## Agregar valores en diccionario.

In [ ]:
X = {}

In [ ]:
X['Col 1'] = 22
X['Col 2'] = 9.8


In [ ]:
print(X)

{'Col 1': 22, 'Col 2': 9.8}


In [ ]:
 Y = {}
 Y[1] = [99, 88, 77]

In [ ]:
print(Y)

{1: [99, 88, 77]}


In [ ]:
A = {}
A['Ciclista A'] = [230, 160, 250, 1000]
A['Ciclista B'] = [200, 180, 240, 1200]
A['Ciclista C'] = [300, 140, 260, 1400]
print(A)

{'Ciclista A': [230, 160, 250, 1000], 'Ciclista B': [200, 180, 240, 1200], 'Ciclista C': [300, 140, 260, 1400]}


In [ ]:
A['Ciclista A'][1] > 140

160

In [ ]:
N = int(input()) # N=3
x = []
y = {}
var = input('Nombre ciclista: ')
x.append(var)
reg = input('Valores del registro: ')
y[x[0]] = reg
var = input('Nombre ciclista: ')
x.append(var)
reg = input('Valores del registro: ')
y[x[1]] = reg
var = input('Nombre ciclista: ')
x.append(var)
reg = input('Valores del registro: ')
y[x[2]] = reg

In [ ]:
N = int(input()) # N=3
x = []
y = {}
for i in range(N):
  var = input('Nombre ciclista: ')
  x.append(var)
  reg = input('Valores del registro: ').split()
  y[x[i]] = reg
print(y)

2
Nombre ciclista: Ciclista A
Valores del registro: 240 160 230 1000
Nombre ciclista: Ciclista B
Valores del registro: 250 180 240 1400
{'Ciclista A': ['240', '160', '230', '1000'], 'Ciclista B': ['250', '180', '240', '1400']}


In [ ]:
int(y['Ciclista A'][1]) >= 140

True

## update()

In [ ]:
A = {'Clave 1': [1, 2, 3]}
B = {'Clave 2': [9, 8, 7]}
print(A)
A.update(B)
print(A)

{'Clave 1': [1, 2, 3]}
{'Clave 1': [1, 2, 3], 'Clave 2': [9, 8, 7]}


In [ ]:
# modificar:
A['Clave 1'] = [6, 5, 4]
A

{'Clave 1': [6, 5, 4], 'Clave 2': [9, 8, 7]}

In [ ]:
A['Clave 1'][0] = 2
A

{'Clave 1': [2, 5, 4], 'Clave 2': [9, 8, 7]}

## del()

In [ ]:
del A['Clave 1']
A

{'Clave 2': [9, 8, 7]}

In [ ]:
A['Clave 1'] = [6, 5, 4]
len(A['Clave 1'])

3

In [ ]:
print(A)
B = list(A)
print(B)
print(A)

{'Clave 2': [9, 8, 7], 'Clave 1': [6, 5, 4]}
['Clave 2', 'Clave 1']
{'Clave 2': [9, 8, 7], 'Clave 1': [6, 5, 4]}


In [ ]:
print(A)
print('Clave 2' in A)
print('Clave 3' in A)

{'Clave 2': [9, 8, 7], 'Clave 1': [6, 5, 4]}
True
False


In [ ]:
print(A)
6 in A['Clave 1']
A['Clave 1'].index(4)

{'Clave 2': [9, 8, 7], 'Clave 1': [6, 5, 4]}


2

In [ ]:
('Llave 1', 9)
('Llave 2', 10)
a = [('Llave 1', 9), ('Llave 2', 10)]
print(type(a))
a = dict([('Llave 1', 9), ('Llave 2', 10)])
print(a)
print(type(a))

<class 'list'>
{'Llave 1': 9, 'Llave 2': 10}
<class 'dict'>


In [ ]:
A = dict(Llave_3 = [2, 3, 4], Llave_4 = ['Cadena de caracteres.'])
A

{'Llave_3': [2, 3, 4], 'Llave_4': ['Cadena de caracteres.']}

In [ ]:
A['Llave_4'].append('Otra Cadena.')
A

{'Llave_3': [2, 3, 4], 'Llave_4': ['Cadena de caracteres.', 'Otra Cadena.']}

In [ ]:
A

{'Llave_3': [2, 3, 4], 'Llave_4': ['Cadena de caracteres.', 'Otra Cadena.']}

In [ ]:
B = A.copy()
B = A
print(B)
print(A)

{'Llave_3': [2, 3, 4], 'Llave_4': ['Cadena de caracteres.', 'Otra cadena', 'Otra cadena']}
{'Llave_3': [2, 3, 4], 'Llave_4': ['Cadena de caracteres.', 'Otra cadena', 'Otra cadena']}


In [ ]:
# ejercicio 1:
N = abs(int(input("Ingrese un valor: ")))

# range(3)      -> 0,1,2
# range(3+1)    -> 0,1,2,3
# range(1, 3+1) ->1,2,3

A = {x: x**2 for x in range(1, N+1)}
print(A)

Ingrese un valor: -3
{}


# Matrices

## crear matriz

In [ ]:
A = [0]
print(A)
A.append(2)
print(A)
A[0] = 5
print(A)

[0]
[0, 2]
[5, 2]


In [ ]:
A = []
print(A)
A.append([99, 88, 77, 66])
print(A)
print(A[0])
A.append([55, 44, 33, 22])
print(A)
print(A[1])
A.append([11, 234, 567, 890])
print(A)

[]
[[99, 88, 77, 66]]
[99, 88, 77, 66]
[[99, 88, 77, 66], [55, 44, 33, 22]]
[55, 44, 33, 22]
[[99, 88, 77, 66], [55, 44, 33, 22], [11, 234, 567, 890]]


In [ ]:
print(A)
print(A[1])
print(A[1][2])

[[99, 88, 77, 66], [55, 44, 33, 22], [11, 234, 567, 890]]
[55, 44, 33, 22]
33


In [ ]:
A = [[99, 88, 77, 66], 
     [55, 44, 33, 22], 
     [11, 234, 567, 890]]

columna = []
print(columna)
columna.append(A[0][1])
print(columna)
columna.append(A[1][1])
print(columna)
columna.append(A[2][1])
print(columna)
# columna = [A[0][1], A[1][1], A[2][1]]

[]
[88]
[88, 44]
[88, 44, 234]


In [ ]:
columna = []
for i in range(3):
  print(columna)
  columna.append(A[i][1])

print(columna)

[]
[88]
[88, 44]
[88, 44, 234]


In [ ]:
A = [[99, 88, 77, 66], 
     [55, 44, 33, 22], 
     [11, 234, 567, 890]]

print(A[0])
print(A[1])
print(A[2])
print('*******')
for fila in A:
  print(fila)
print('*******')
for fila in A:
  print(fila[1])

[99, 88, 77, 66]
[55, 44, 33, 22]
[11, 234, 567, 890]
*******
[99, 88, 77, 66]
[55, 44, 33, 22]
[11, 234, 567, 890]
*******
88
44
234


In [ ]:
A = [[99, 88, 77, 66], 
     [55, 44, 33, 22], 
     [11, 234, 567, 890]]
columna = []
for fila in A:
  columna.append(fila[1])
print(columna)

[88, 44, 234]


In [ ]:
A = [[99, 88, 77, 66], 
     [55, 44, 33, 22], 
     [11, 234, 567, 890]]
print(A)
A[0].append(100)
print(A)
A[1].append(200)
print(A)
A[2].append(400)
print(A)

[[99, 88, 77, 66], [55, 44, 33, 22], [11, 234, 567, 890]]
[[99, 88, 77, 66, 100], [55, 44, 33, 22], [11, 234, 567, 890]]
[[99, 88, 77, 66, 100], [55, 44, 33, 22, 200], [11, 234, 567, 890]]
[[99, 88, 77, 66, 100], [55, 44, 33, 22, 200], [11, 234, 567, 890, 400]]


## suma de matrices.

In [ ]:
X = [[2, 3, 6],
     [4, 1, 5]]
Y = [[8, 7, 4],
     [6, 9, 5]]
R = [[0, 0, 0],
     [0, 0, 0]]

for i in range(2):
  for j in range(3):
    R[i][j] = X[i][j] + Y[i][j]

In [ ]:
print(R)

[[10, 10, 10], [10, 10, 10]]


In [ ]:
X = [[2, 3, 6],
     [4, 1, 5]]
Y = [[8, 7, 4],
     [6, 9, 5]]
R = [[],[]]
i=0
R[i].append(X[i][0]+Y[i][0])
R[i].append(X[i][1]+Y[i][1])
R[i].append(X[i][2]+Y[i][2])
i=1
R[i].append(X[i][0]+Y[i][0])
R[i].append(X[i][1]+Y[i][1])
R[i].append(X[i][2]+Y[i][2])

"""for i in range(2):
  for j in range(3):
    R[i][j] = X[i][j] + Y[i][j]
"""

'for i in range(2):\n  for j in range(3):\n    R[i][j] = X[i][j] + Y[i][j]\n'

In [ ]:
R = [[],[]]
for i in range(2):
  for j in range(3):
    R[i].append(X[i][j]+Y[i][j])


In [ ]:
for j in range(3):
  R[i].append(X[i][j]+Y[i][j])


In [ ]:
for fila in R:
  print(fila)

[10, 10, 10]
[10, 10, 10]


## Transpuesta de una matriz

In [ ]:
X = [[2, 3, 6],
     [4, 1, 5],
     [9, 8, 7]]
T = [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]]

for i in range(3):
  for j in range(3):
    T[j][i]= X[i][j]

In [ ]:
for fila in X:
  print(fila)
print("****")
for fila in T:
  print(fila)

[2, 3, 6]
[4, 1, 5]
[9, 8, 7]
****
[2, 4, 9]
[3, 1, 8]
[6, 5, 7]


## Ejemplo de llenar una matriz cuadrada por usuario.

In [ ]:
n = int(input("Ingrese las dimensiones de la matriz: "))
# Definir los espacios de X:
X = list(range(n)) # X = [0,1,2]
for i in range(n): # X[2] =[0,1,2] 
  X[i] = list(range(n))
# Ingreso de los valores de 'X' por el usuario:
for i in range(n):
  for j in range(n):
    print("Fila = ",i," Columna = ",j)
    X[i][j] = int(input("Ingrese valor: "))
print("La matriz ingresada por usuario es: ")
for filas in X:
  print(filas)
print("******")
print(X)

Ingrese las dimensiones de la matriz: 2
Fila =  0  Columna =  0
Ingrese valor: 1
Fila =  0  Columna =  1
Ingrese valor: 2
Fila =  1  Columna =  0
Ingrese valor: 3
Fila =  1  Columna =  1
Ingrese valor: 4
La matriz ingresada por usuario es: 
[1, 2]
[3, 4]
******
[[1, 2], [3, 4]]


In [ ]:
n = int(input("Ingrese las dimensiones de la matriz: "))
X = list(range(n)) # X = [0,1,2]
for i in range(n): # X[2] =[0,1,2] 
  X[i] = list(range(n))

Ingrese las dimensiones de la matriz: 3


In [ ]:
for filas in X:
  print(filas)

[1, 2]
[3, 4]


## Multiplicación entre matrices:

In [ ]:
A = [[4, 7, 2],
     [3, 9, 11]]
B = [[2 ,1],
     [8, 3],
     [5, 2]]
R = [[0, 0],
     [0, 0]]
for i in range(2):
  for j in range(2):
    for k in range(3):
      R[i][j] += A[i][k]*B[k][j]

for fila in R:
  print(fila)

[74, 29]
[133, 52]


# Numpy

In [ ]:
A = [1, 2, 3, 4, 5, 6]
print(A)

[1, 2, 3, 4, 5, 6]


In [ ]:
import numpy as np

In [ ]:
Anp = np.array([1, 2, 3, 4, 5, 6])
print(Anp)
print(type(Anp))
print(Anp[0])
print(Anp[-1])
print(Anp[0:3])
print(Anp[-3:])

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
6
[1 2 3]
[4 5 6]


## Suma de matrices con numpy

In [ ]:
A = np.array([[2, 3, 4],
              [8, 5, 1]])
B = np.array([[8, 7, 6],
              [2, 5, 9]])
print(A)
print(B)
C = A + B
print(C)

[[2 3 4]
 [8 5 1]]
[[8 7 6]
 [2 5 9]]
[[10 10 10]
 [10 10 10]]


## Multiplicación de matrices en numpy

In [ ]:
A = np.array([[4, 7, 2],
              [3, 9, 11]])
B = np.array([[2, 1],
              [8, 3],
              [5, 2]])
print(A)
print(B)
C = A.dot(B)
print(C)

[[ 4  7  2]
 [ 3  9 11]]
[[2 1]
 [8 3]
 [5 2]]
[[ 74  29]
 [133  52]]


## Transpuesta en numpy

In [ ]:
A = np.array([[4, 7, 2],
              [3, 9, 11]])
print(A)
C = A.transpose()
print(C)

[[ 4  7  2]
 [ 3  9 11]]
[[ 4  3]
 [ 7  9]
 [ 2 11]]


## Acceso

In [ ]:
A = np.array([[99, 88, 77, 66], 
              [55, 44, 33, 22], 
              [11, 234, 567, 890]])
print(A)
print(A[0])
print(A[1][1])

[[ 99  88  77  66]
 [ 55  44  33  22]
 [ 11 234 567 890]]
[99 88 77 66]
44


In [ ]:
# Acceso a columnas:
print(A)
print(A[0][2])
print(A[0, 2])
print(A[:,1])
print(A[:2,1])
print(A[0:2,1:3])

[[ 99  88  77  66]
 [ 55  44  33  22]
 [ 11 234 567 890]]
77
77
[ 88  44 234]
[88 44]
[[88 77]
 [44 33]]


In [ ]:
C = A[0:2,1:3]
print(C)
D = C.transpose()
print(D)

[[88 77]
 [44 33]]
[[88 44]
 [77 33]]


In [ ]:
print(A[:,1])
C = np.array(A[:,1].transpose())
print(C)

[ 88  44 234]
[ 88  44 234]


# Funciones.

In [ ]:
print("Palabra....")
A = int("2")

Palabra....


In [ ]:
# Declaración de la función:
def sumarn(a=0, b=0):  #p1 = A, p2 = B
  return a + b

A = int(input("Ingrese 1mer valor: "))
B = int(input("Ingrese 2do valor: "))

# Llamado a la función:
R = sumarn(A, B)
print(R)
print(sumarn(4, 6))
print(sumarn())
print(sumarn(9))

Ingrese 1mer valor: 5
Ingrese 2do valor: 2
7
10
0
9


In [ ]:
def bienve(p1):
  print("Bienvenido señor", p1)

nombre = input("Ingrese su nombre: ")

bienve(nombre)

Ingrese su nombre: Cesar
Bienvenido señor Cesar


# Reto 4

In [ ]:
def leer_datos():
  n , k = [int(x) for x in input().split()]
  b = [int(x) for x in input().split()]
  return n, k, b

N, K, B = leer_datos()

print(B)

5 1
1 2 3 1 2
[1, 2, 3, 1, 2]


In [ ]:
dicci = {1: 0, 2: 1, 3: 2}